from django.urls import path
from .import views
urlpatterns = [

    path('',views.index, name='homepage'),
    path('signin',views.index1, name='signup'),
    path('admin_login', views.alogin, name='signup'),
    path('drlogin', views.drlogin, name='signup'),
    path('dr_login', views.dr_login, name='signup'),
    path('patient_login', views.plogin, name='signup'),
    path('lab_login', views.llogin, name='signup'),
    path('chemist_login', views.clogin, name='signup'),
    path('alogin', views.adminlogin, name='signup'),
    path('manage_doctor', views.manage_doctor, name='signup'),
    path('adddoc', views.adddoc, name='adddoctor'),
    path('reg_doctor', views.reg_doctor, name='adddoctor'),
    path('manage_disease', views.manage_disease, name='signup'),
    path('adddis', views.adddis, name='adddisease'),
    path('reg_disease', views.reg_disease, name='adddoctor'),
    path('searchid', views.searchid, name='search'),
    path('showdoc', views.showdoc, name='search'),
    path('addappointment', views.addappointment, name='appoinments'),
    ####rk
    path('delA', views.delA, name='delete'),
    path('homep', views.homep, name='patient'),
    path('payp', views.payp, name='patient'),
    path('docapprove', views.docapprove, name='apppointments'),
    path('docA', views.docA, name='apppointments'),

    path('showappointment', views.showappointment, name='appoinments'),
    path('showpay', views.showpay, name='pay'),
    path('addpay', views.addpay, name='pay'),
    path('chat', views.chat, name='chat'),
    path('chatread', views.chatread, name='chat'),
    path('chatview', views.chatview, name='chat'),
    path('pred', views.pred, name='prediction'),
    path('searchdisease', views.searchdisease, name='searchdisease'),
    path('chemisthome', views.chemisthome, name='chemist'),
    path('cart', views.cart, name='chemist'),
    path('check', views.check, name='chemist'),
    path('checkpay', views.checkpay, name='chemist'),
    path('checkship', views.checkship, name='chemist'),
    path('manage_patient', views.manage_patient, name='signup'),
    path('addmed', views.addmed, name='chemist'),
    path('medstock', views.medstock, name='chemist'),
    path('pres', views.pres, name='chemist'),
    path('feedback', views.feedback, name='feedback'),
    #path('doctorhome', views.doctorhome, name='signup'),
    path('adminshome', views.adminshome, name='signup'),
    path('delmed', views.delmed, name='chemist'),
    path('updatestock', views.updatestock, name='chemist'),
    path('updatestock1', views.updatestock1, name='chemist'),

    path('labhome', views.labhome, name='signup'),
    path('updatedoctor',views.updatedoctor, name='update'),
    #path('checkship', views.doctorhome, name='chemist'),
   # path('addpati', views.addpati, name='addpatient'),
    path('reg_patient', views.reg_patient, name='addpatient'),
    path('manage_chemist', views.manage_chemist, name='signup'),
    path('reg_chemist', views.reg_chemist, name='addchemist'),
    path('showp', views.showp, name='addchemist'),
    path('doclist', views.doclist, name='admin/doctor'),
    path('docabout', views.docabout, name='admin/doctor'),
    path('editdoc', views.editdoc, name='admin/doctor'),
    path('dislist', views.dislist, name='admin/disease'),
    path('patientlist', views.patientlist, name='admin/patient'),
    path('chemlist', views.chemlist, name='admin/chemist'),
    path('patientlistdoc', views.patientlistdoc, name='patient'),
    path('adddis', views.adddis, name='admindisease'),
    path('editdis', views.editdis, name='editdisease'),
    path('editpatient', views.editpatient, name='edit'),
    path('addpat', views.addpat, name='patient'),
    path('addchem', views.addchem, name='chemist'),
    path('fedback', views.fedback, name='feedback'),
    path('sendfeed', views.sendfeed, name='chemist'),
    path('chatbot', views.chatbot, name='chemist'),
    path('manage_lab', views.manage_lab, name='signup'),
   # path('addlab', views.addlab, name='addlab'),
    path('reg_lab', views.reg_lab, name='addlab'),
    path('lablist', views.lablist, name='addlab'),
    path('addreport', views.addreport, name='addlab'),
    path('uploadtest', views.uploadtest, name='addlab'),
    path('patient_loginhome', views.patient_login, name='addlab'),
#manasm is the king
    path('labreport', views.labreport, name="homepage"),
    path('addreport', views.addreport, name="homepage"),
    path('addreports', views.addreports, name="homepage"),
    path('drp', views.drp, name="lab"),
    path('drp2', views.drp2, name="lab"),
    path('reportdoc', views.reportdoc, name="lab"),

    path('sendmed1', views.sendmed1, name="homepage"),
    path('dispatch', views.dispatch, name="homepage"),
    path('sendmed2', views.sendmed2, name="homepage"),



]